version: "3"

services:
  server:
    container_name: server-whale-hunter
    build: ./server
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    command: bash -c "python manage.py runserver 0.0.0.0:$SERVER_PORT"
    working_dir: /var/www/server
    volumes:
      - ./server:/var/www/server
    environment:
      - DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
    env_file:
      - .env
    depends_on:
      - redis
      - celery

  client:
    container_name: client-whale-hunter
    build:
      context: ./client
      dockerfile: docker/development/Dockerfile
    working_dir: /var/www/client
    ports:
      - "$CLIENT_PORT:$CLIENT_PORT"
    volumes:
      - ./client:/var/www/client
      - ./server:/var/www/server
    environment:
      - REACT_APP_GRAPHQL_ENDPOINT=${REACT_APP_GRAPHQL_ENDPOINT}

  redis:
    image: "redis:latest"
    container_name: redis-whale-hunter
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  celery:
    build: ./server
    container_name: celery-whale-hunter
    command: bash -c "poetry run celery -A server worker -l info"
    working_dir: /var/www/server
    volumes:
      - ./server:/var/www/server
    environment:
      - DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
    env_file:
      - .env
    depends_on:
      - redis
